const changeColorVariablesConstant = [
    "REACT_APP_TOAST_SUCCESS_DARK_BG",
    "REACT_APP_TOAST_SUCCESS_DARK_TEXT",
    "REACT_APP_TOAST_INFO_DARK_BG",
    "REACT_APP_TOAST_INFO_DARK_TEXT",
    "REACT_APP_TOAST_FAIL_DARK_BG",
    "REACT_APP_TOAST_FAIL_DARK_TEXT",
    "REACT_APP_DISABLE_BG_DARK_COLOR",
    "REACT_APP_DISABLE_TEXT_DARK_COLOR",
    "REACT_APP_FIRST_ICON_DARK_COLOR",
    "REACT_APP_SECOND_ICON_DARK_COLOR",
    "REACT_APP_FIRST_BACKGROUND_DARK_COLOR",
    "REACT_APP_SECOND_BACKGROUND_DARK_COLOR",
    "REACT_APP_PAGE_DARK_COLOR",
    "REACT_APP_FIRST_TEXT_DARK_COLOR",
    "REACT_APP_SECOND_TEXT_DARK_COLOR",
    "REACT_APP_FIRST_BORDER_DARK_COLOR",
    "REACT_APP_SECOND_BORDER_DARK_COLOR",
    "REACT_APP_FIRST_DARK_SHADOW",
    "REACT_APP_FIRST_MATERIAL_DARK_COLOR",
]

export default changeColorVariablesConstant