const changeColorVariablesConstant = [
    "REACT_APP_FIRST_BACKGROUND_DARK_COLOR",
    "REACT_APP_FIRST_TEXT_DARK_COLOR",
    "REACT_APP_THIRD_TEXT_DARK_COLOR",
    "REACT_APP_FIRST_BORDER_DARK_COLOR",
    "REACT_APP_FIRST_MATERIAL_DARK_COLOR",
    "REACT_APP_DISABLE_BG_DARK_COLOR",
    "REACT_APP_DISABLE_TEXT_DARK_COLOR",
    "REACT_APP_TOAST_SUCCESS_DARK_BG",
    "REACT_APP_TOAST_SUCCESS_DARK_TEXT",
    "REACT_APP_TOAST_INFO_DARK_BG",
    "REACT_APP_TOAST_INFO_DARK_TEXT",
    "REACT_APP_TOAST_FAIL_DARK_BG",
    "REACT_APP_TOAST_FAIL_DARK_TEXT",
]

export default changeColorVariablesConstant