const faTextConstant = {
    loginTitle: `ورود به ${process.env.REACT_APP_NAME}`,
    loginDesc: "لطفا ایمیل و رمز عبورتون وارد کنید",
    registerTitle: `ثبت‌نام در ${process.env.REACT_APP_NAME}`,
    registerDesc: "لطفا ایمیل و رمز عبور دلخواهتون رو وارد کنید",
    privacyIntro: "ورود شما به معنی قبول",
    privacyTitle: "قوانین حریم خصوصی",
    privacyEnd: "می‌باشد",
    submit: "تایید",
    login: "ورود",
    register: "ثبت‌نام",
    email: "ایمیل",
    emailPlaceholder: "ایمیل خود را وارد کنید",
    password: "رمز عبور",
    passwordPlaceholder: "رمز عبور دلخواه خود را وارد کنید",
    passwordConfirm: "تکرار رمز عبور",
    passwordConfirmPlaceholder: "رمز عبور خود را مجددا وارد کنید",
    haveAcc: "حساب کاربری دارم",
    dontHaveAcc: "حساب کاربری ندارید؟",
    dontHaveAccDesc: "ثبت‌نام کنید",
    sendVideo: "ارسال ویدئو",
    home: "خانه",
    archive: "آرشیو",
    account: "پروفایل",
    showAll: "مشاهده همه",
    notFound: "موردی یافت نشد",
    editAccount: "ویرایش پروفایل",
    setting: "تنظیمات",
    darkMode: "حالت شب",
    chooseLanguage: "انتخاب زبان",
    aboutUs: "درباره ما",
    logout: "خروج",
    tools: "جعبه ابزار دانشجویی",
    portal: "پرتال دانشجویی",
    food: "سامانه تغذیه",
    other: "سایر خدمات",
    views: " بازدید",
    searchHolder: "عبارت مورد نظر را برای جستجو وارد کنید",
    categories: count => `دسته‌بندی‌ها ${count ? `(${count})` : ""}`,
    similarVideos: "ویدئوهای مشابه",
    loginRegister: "ثبت‌نام / ورود",
}

export default faTextConstant